/**
 * .fabrk/ directory generation — manifest, next.config, gitignore.
 */
/* eslint-disable no-console */

import chalk from 'chalk';
import fs from 'fs-extra';
import path from 'path';
import { hasFabrkConfig, findFiles } from './helpers';

export interface FabrkDirOptions {
  root: string;
  configPath: string | null;
}

export function generateFabrkDir({ root, configPath }: FabrkDirOptions): void {
  const fabrkDir = path.join(root, '.fabrk');
  fs.ensureDirSync(fabrkDir);

  // Generate manifest.json for AI agents
  const manifest = generateManifest(root);
  fs.writeJsonSync(path.join(fabrkDir, 'manifest.json'), manifest, { spaces: 2 });

  // Generate next.config.mjs from fabrk config
  generateNextConfig(fabrkDir, root);

  // Generate .gitignore if not present
  const gitignorePath = path.join(fabrkDir, '.gitignore');
  if (!fs.existsSync(gitignorePath)) {
    fs.writeFileSync(gitignorePath, '*\n');
  }

  if (configPath) {
    console.log(chalk.green('[FABRK]') + chalk.dim(` Generated .fabrk/ from ${path.basename(configPath)}`));
  }
}

function generateNextConfig(fabrkDir: string, root: string): void {
  // Read fabrk.config if it exists and extract framework-relevant settings
  const hasConfig = hasFabrkConfig(root);

  // Detect installed @fabrk packages for transpilePackages
  const pkgPath = path.join(root, 'package.json');
  let fabrkPackages: string[] = [];
  if (fs.existsSync(pkgPath)) {
    const pkg = fs.readJsonSync(pkgPath);
    const allDeps = { ...pkg.dependencies, ...pkg.devDependencies };
    fabrkPackages = Object.keys(allDeps).filter(d => d.startsWith('@fabrk/'));
  }

  const nextConfig = `/** @type {import('next').NextConfig} */
// Auto-generated by FABRK CLI — do not edit manually.
// Source: ${hasConfig ? 'fabrk.config.ts' : 'defaults'}

const nextConfig = {
  // Transpile FABRK packages for proper ESM/CJS resolution
  transpilePackages: ${JSON.stringify(fabrkPackages)},

  // Strict React mode for better development experience
  reactStrictMode: true,

  // Enable experimental features used by FABRK
  experimental: {
    // Enable server actions for FABRK form handling
    serverActions: { bodySizeLimit: '2mb' },
  },
}

export default nextConfig
`;

  fs.writeFileSync(path.join(fabrkDir, 'next.config.mjs'), nextConfig);
}

export function generateManifest(root: string): object {
  const pkgPath = path.join(root, 'package.json');
  const pkg = fs.existsSync(pkgPath) ? fs.readJsonSync(pkgPath) : {};
  const allDeps = { ...pkg.dependencies, ...pkg.devDependencies };
  const fabrkPackages = Object.keys(allDeps).filter(d => d.startsWith('@fabrk/'));

  // Scan for components
  const componentDirs = ['src/components', 'components', 'src/components/ui'];
  const components: string[] = [];
  for (const dir of componentDirs) {
    const fullDir = path.join(root, dir);
    if (fs.existsSync(fullDir)) {
      const files = findFiles(fullDir, ['.tsx', '.jsx']);
      components.push(...files.map(f => path.relative(root, f)));
    }
  }

  // Scan for pages
  const pageDirs = ['src/app', 'app'];
  const pages: string[] = [];
  for (const dir of pageDirs) {
    const fullDir = path.join(root, dir);
    if (fs.existsSync(fullDir)) {
      const files = findFiles(fullDir, ['.tsx', '.jsx']).filter(f => f.endsWith('page.tsx') || f.endsWith('page.jsx'));
      pages.push(...files.map(f => path.relative(root, f)));
    }
  }

  return {
    name: pkg.name || 'unknown',
    version: pkg.version || '0.0.0',
    framework: 'fabrk',
    runtime: allDeps['@fabrk/framework'] ? 'fabrk' : 'nextjs',
    generatedAt: new Date().toISOString(),
    packages: fabrkPackages,
    components,
    pages,
    hasConfig: hasFabrkConfig(root),
    features: {
      auth: fabrkPackages.includes('@fabrk/auth'),
      payments: fabrkPackages.includes('@fabrk/payments'),
      email: fabrkPackages.includes('@fabrk/email'),
      storage: fabrkPackages.includes('@fabrk/storage'),
      security: fabrkPackages.includes('@fabrk/security'),
      ai: fabrkPackages.includes('@fabrk/ai'),
      themes: fabrkPackages.includes('@fabrk/design-system'),
    },
  };
}
