import { defineConfig } from 'tsup'

export default defineConfig({
  entry: [
    'src/index.ts',
    'src/cli.ts',
    'src/fabrk.ts',
    'src/client/use-agent.ts',
    'src/client/navigation.ts',
    'src/client/link.tsx',
    'src/client/image.tsx',
    'src/client/dynamic.ts',
    'src/client/script.ts',
    'src/client/form.tsx',
    'src/client/use-form-state.ts',
    'src/agents/define-agent.ts',
    'src/tools/define-tool.ts',
    'src/build/agents-md.ts',
    'src/runtime/worker-entry.ts',
  ],
  format: ['esm'],
  dts: true,
  sourcemap: true,
  clean: true,
  splitting: true,
  external: [
    'react',
    'react-dom',
    'react-server-dom-webpack',
    'vite',
    '@vitejs/plugin-rsc',
    '@vitejs/plugin-react',
    'rsc-html-stream',
    'satori',
    '@resvg/resvg-js',
  ],
})
