import type { ModeColor } from './mode-types';

/** Color token values for the default terminal theme. */
export const modeColorTokens: ModeColor = {
  bg: {
    base: 'bg-background',
    surface: 'bg-card',
    surfaceRaised: 'bg-card',
    elevated: 'bg-popover',
    accent: 'bg-accent',
    accentMuted: 'bg-accent/10',
    accentHover: 'bg-accent/90',
    primarySubtle: 'bg-primary/5',
    primaryLight: 'bg-primary/10',
    successSubtle: 'bg-success/20',
    danger: 'bg-destructive',
    dangerMuted: 'bg-destructive/10',
    success: 'bg-success',
    successMuted: 'bg-success/10',
    warning: 'bg-warning',
    warningMuted: 'bg-warning/10',
    info: 'bg-info',
    infoMuted: 'bg-info/10',
    muted: 'bg-muted',
    mutedSubtle: 'bg-muted/20',
    mutedLight: 'bg-muted/30',
    mutedMedium: 'bg-muted/50',
    secondary: 'bg-secondary',
  },
  text: {
    primary: 'text-foreground',
    secondary: 'text-card-foreground',
    muted: 'text-muted-foreground',
    inverse: 'text-accent-foreground',
    accent: 'text-accent',
    danger: 'text-destructive',
    dangerOnColor: 'text-destructive-foreground',
    success: 'text-success',
    successOnColor: 'text-success-foreground',
    warning: 'text-warning',
    warningOnColor: 'text-warning-foreground',
    info: 'text-info',
    infoOnColor: 'text-info-foreground',
  },
  border: {
    default: 'border-border',
    focus: 'border-ring',
    accent: 'border-primary',
    danger: 'border-destructive',
    success: 'border-success',
    warning: 'border-warning',
    accentSubtle: 'border-primary/30',
    mutedSubtle: 'border-muted-foreground/30',
  },
  icon: {
    primary: 'text-foreground',
    secondary: 'text-card-foreground',
    muted: 'text-muted-foreground',
    accent: 'text-accent',
    danger: 'text-destructive',
    success: 'text-success',
    warning: 'text-warning',
    info: 'text-info',
  },
};
