import type { Route } from "./router";
import fs from "node:fs";

/**
 * Generate a server entry module that statically imports all route modules
 * and exports a `handleRequest(req: Request): Promise<Response>` function.
 *
 * The generated module is written to a temp file and used as the SSR build
 * entry point. This ensures all route code is bundled into a single file
 * during production build.
 */
export function generateServerEntry(routes: Route[], appDir: string): string {
  const imports: string[] = [];
  const routeRegistrations: string[] = [];

  // Import all page and API route modules
  for (let i = 0; i < routes.length; i++) {
    const route = routes[i];
    const varName = `route_${i}`;
    imports.push(`import * as ${varName} from ${JSON.stringify(route.filePath)};`);

    // Serialize the route regex as constructor args so it survives bundling
    const regexSource = route.regex.source;
    const regexFlags = route.regex.flags;

    routeRegistrations.push(`  {
    pattern: ${JSON.stringify(route.pattern)},
    regex: new RegExp(${JSON.stringify(regexSource)}, ${JSON.stringify(regexFlags)}),
    paramNames: ${JSON.stringify(route.paramNames)},
    type: ${JSON.stringify(route.type)},
    module: ${varName},
    filePath: ${JSON.stringify(route.filePath)},
    layoutPaths: ${JSON.stringify(route.layoutPaths)},${route.catchAll ? "\n    catchAll: true," : ""}${route.optionalCatchAll ? "\n    optionalCatchAll: true," : ""}${route.errorPath ? `\n    errorPath: ${JSON.stringify(route.errorPath)},` : ""}${route.loadingPath ? `\n    loadingPath: ${JSON.stringify(route.loadingPath)},` : ""}${route.notFoundPath ? `\n    notFoundPath: ${JSON.stringify(route.notFoundPath)},` : ""}
  }`);
  }

  // Import layout modules
  const layoutPaths = new Set<string>();
  for (const route of routes) {
    for (const lp of route.layoutPaths) {
      layoutPaths.add(lp);
    }
  }

  const layoutImports: string[] = [];
  const layoutMap: string[] = [];
  let layoutIdx = 0;
  for (const lp of layoutPaths) {
    const varName = `layout_${layoutIdx++}`;
    layoutImports.push(`import * as ${varName} from ${JSON.stringify(lp)};`);
    layoutMap.push(`  ${JSON.stringify(lp)}: ${varName},`);
  }

  // Import error/loading/not-found boundaries
  const boundaryPaths = new Set<string>();
  for (const route of routes) {
    if (route.errorPath) boundaryPaths.add(route.errorPath);
    if (route.loadingPath) boundaryPaths.add(route.loadingPath);
    if (route.notFoundPath) boundaryPaths.add(route.notFoundPath);
  }

  const boundaryImports: string[] = [];
  const boundaryMap: string[] = [];
  let boundaryIdx = 0;
  for (const bp of boundaryPaths) {
    const varName = `boundary_${boundaryIdx++}`;
    boundaryImports.push(`import * as ${varName} from ${JSON.stringify(bp)};`);
    boundaryMap.push(`  ${JSON.stringify(bp)}: ${varName},`);
  }

  // Check for global-error at app root
  const globalErrorImport = findGlobalError(routes, appDir);

  return `// Auto-generated by fabrk build — do not edit
${imports.join("\n")}
${layoutImports.join("\n")}
${boundaryImports.join("\n")}
${globalErrorImport ? `import * as globalError from ${JSON.stringify(globalErrorImport)};` : ""}

export const routes = [
${routeRegistrations.join(",\n")}
];

export const layoutModules = {
${layoutMap.join("\n")}
};

export const boundaryModules = {
${boundaryMap.join("\n")}
};

${globalErrorImport ? "export { globalError };" : "export const globalError = null;"}
`;
}

function findGlobalError(_routes: Route[], appDir: string): string | null {
  const extensions = [".tsx", ".ts", ".jsx", ".js"];
  for (const ext of extensions) {
    const candidate = `${appDir}/global-error${ext}`;
    if (fs.existsSync(candidate)) return candidate;
  }
  return null;
}
