#!/usr/bin/env node

/**
 * fabrk CLI — Primary interface for the FABRK Framework
 *
 * FABRK wraps Next.js the same way Next.js wraps React.
 * This CLI owns the developer lifecycle: create, dev, build, add, generate.
 *
 * @example
 * ```bash
 * fabrk create my-app        # Scaffold a new FABRK project
 * fabrk dev                   # Dev server (generates .fabrk/ configs, wraps next dev)
 * fabrk build                 # Production build
 * fabrk add button card       # Add UI components (shadcn-style copy)
 * fabrk add-theme terminal    # Install a design system theme
 * fabrk add auth              # Add a feature module
 * fabrk generate component X  # Generate scaffolds
 * fabrk doctor                # Diagnose issues
 * fabrk info                  # Show project info
 * ```
 */

import { program } from 'commander';
import prompts from 'prompts';
import chalk from 'chalk';
import ora from 'ora';
import fs from 'fs-extra';
import path from 'path';
import { execSync, spawn } from 'child_process';

const VERSION = '0.1.0';

// ============================================================================
// HELPERS
// ============================================================================

function findProjectRoot(): string {
  let dir = process.cwd();
  while (dir !== path.dirname(dir)) {
    if (fs.existsSync(path.join(dir, 'fabrk.config.ts')) ||
        fs.existsSync(path.join(dir, 'fabrk.config.js'))) {
      return dir;
    }
    if (fs.existsSync(path.join(dir, 'package.json'))) {
      return dir;
    }
    dir = path.dirname(dir);
  }
  return process.cwd();
}

function hasFabrkConfig(root: string): boolean {
  return fs.existsSync(path.join(root, 'fabrk.config.ts')) ||
         fs.existsSync(path.join(root, 'fabrk.config.js'));
}

function runCommand(cmd: string, args: string[], cwd: string): void {
  const child = spawn(cmd, args, {
    cwd,
    stdio: 'inherit',
    shell: true,
  });

  child.on('close', (code) => {
    process.exit(code ?? 0);
  });

  child.on('error', (err) => {
    console.error(chalk.red(`Failed to run ${cmd}: ${err.message}`));
    process.exit(1);
  });
}

function findFiles(dir: string, extensions: string[]): string[] {
  const files: string[] = [];
  if (!fs.existsSync(dir)) return files;

  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory() && !entry.name.startsWith('.') && entry.name !== 'node_modules') {
      files.push(...findFiles(fullPath, extensions));
    } else if (entry.isFile() && extensions.some(ext => entry.name.endsWith(ext))) {
      files.push(fullPath);
    }
  }
  return files;
}

function toKebabCase(str: string): string {
  return str
    .replace(/([a-z])([A-Z])/g, '$1-$2')
    .replace(/[\s_]+/g, '-')
    .toLowerCase();
}

function toPascalCase(str: string): string {
  return str
    .replace(/[-_\s]+(.)?/g, (_, c) => (c ? c.toUpperCase() : ''))
    .replace(/^(.)/, (_, c) => c.toUpperCase());
}

// ============================================================================
// .FABRK/ DIRECTORY GENERATION
// ============================================================================

interface FabrkDirOptions {
  root: string;
  configPath: string | null;
}

function generateFabrkDir({ root, configPath }: FabrkDirOptions): void {
  const fabrkDir = path.join(root, '.fabrk');
  fs.ensureDirSync(fabrkDir);

  // Generate manifest.json for AI agents
  const manifest = generateManifest(root);
  fs.writeJsonSync(path.join(fabrkDir, 'manifest.json'), manifest, { spaces: 2 });

  // Generate next.config.mjs from fabrk config
  generateNextConfig(fabrkDir, root);

  // Generate .gitignore if not present
  const gitignorePath = path.join(fabrkDir, '.gitignore');
  if (!fs.existsSync(gitignorePath)) {
    fs.writeFileSync(gitignorePath, '*\n');
  }

  if (configPath) {
    console.log(chalk.green('[FABRK]') + chalk.dim(` Generated .fabrk/ from ${path.basename(configPath)}`));
  }
}

function generateNextConfig(fabrkDir: string, root: string): void {
  // Read fabrk.config if it exists and extract framework-relevant settings
  const hasConfig = hasFabrkConfig(root);

  // Detect installed @fabrk packages for transpilePackages
  const pkgPath = path.join(root, 'package.json');
  let fabrkPackages: string[] = [];
  if (fs.existsSync(pkgPath)) {
    const pkg = fs.readJsonSync(pkgPath);
    const allDeps = { ...pkg.dependencies, ...pkg.devDependencies };
    fabrkPackages = Object.keys(allDeps).filter(d => d.startsWith('@fabrk/'));
  }

  const nextConfig = `/** @type {import('next').NextConfig} */
// Auto-generated by FABRK CLI — do not edit manually.
// Source: ${hasConfig ? 'fabrk.config.ts' : 'defaults'}

const nextConfig = {
  // Transpile FABRK packages for proper ESM/CJS resolution
  transpilePackages: ${JSON.stringify(fabrkPackages)},

  // Strict React mode for better development experience
  reactStrictMode: true,

  // Enable experimental features used by FABRK
  experimental: {
    // Enable server actions for FABRK form handling
    serverActions: { bodySizeLimit: '2mb' },
  },
}

export default nextConfig
`;

  fs.writeFileSync(path.join(fabrkDir, 'next.config.mjs'), nextConfig);
}

function generateManifest(root: string): object {
  const pkgPath = path.join(root, 'package.json');
  const pkg = fs.existsSync(pkgPath) ? fs.readJsonSync(pkgPath) : {};
  const allDeps = { ...pkg.dependencies, ...pkg.devDependencies };
  const fabrkPackages = Object.keys(allDeps).filter(d => d.startsWith('@fabrk/'));

  // Scan for components
  const componentDirs = ['src/components', 'components', 'src/components/ui'];
  const components: string[] = [];
  for (const dir of componentDirs) {
    const fullDir = path.join(root, dir);
    if (fs.existsSync(fullDir)) {
      const files = findFiles(fullDir, ['.tsx', '.jsx']);
      components.push(...files.map(f => path.relative(root, f)));
    }
  }

  // Scan for pages
  const pageDirs = ['src/app', 'app'];
  const pages: string[] = [];
  for (const dir of pageDirs) {
    const fullDir = path.join(root, dir);
    if (fs.existsSync(fullDir)) {
      const files = findFiles(fullDir, ['.tsx', '.jsx']).filter(f => f.endsWith('page.tsx') || f.endsWith('page.jsx'));
      pages.push(...files.map(f => path.relative(root, f)));
    }
  }

  return {
    name: pkg.name || 'unknown',
    version: pkg.version || '0.0.0',
    framework: 'fabrk',
    runtime: 'nextjs',
    generatedAt: new Date().toISOString(),
    packages: fabrkPackages,
    components,
    pages,
    hasConfig: hasFabrkConfig(root),
    features: {
      auth: fabrkPackages.includes('@fabrk/auth'),
      payments: fabrkPackages.includes('@fabrk/payments'),
      email: fabrkPackages.includes('@fabrk/email'),
      storage: fabrkPackages.includes('@fabrk/storage'),
      security: fabrkPackages.includes('@fabrk/security'),
      ai: fabrkPackages.includes('@fabrk/ai'),
      mcp: fabrkPackages.includes('@fabrk/mcp'),
      themes: fabrkPackages.includes('@fabrk/themes') || fabrkPackages.includes('@fabrk/design-system'),
    },
  };
}

// ============================================================================
// TEMPLATES
// ============================================================================

interface TemplateChoice {
  title: string;
  value: string;
  description: string;
}

const TEMPLATES: TemplateChoice[] = [
  { title: 'Basic', value: 'basic', description: 'Minimal setup with core components' },
  { title: 'AI SaaS', value: 'ai-saas', description: 'Full AI features with cost tracking and validation' },
  { title: 'Dashboard', value: 'dashboard', description: 'Analytics-focused with charts and KPIs' },
];

const AVAILABLE_THEMES = ['terminal', 'swiss'] as const;

const FEATURE_MODULES = ['auth', 'payments', 'email', 'storage', 'security', 'ai', 'mcp'] as const;

// ============================================================================
// COMMAND: fabrk create
// ============================================================================

program
  .name('fabrk')
  .description('FABRK Framework CLI — The AI-first React meta-framework')
  .version(VERSION);

program
  .command('create [project-name]')
  .description('Create a new FABRK application')
  .option('-t, --template <template>', 'Template to use (basic|ai-saas|dashboard)')
  .option('--no-install', 'Skip dependency installation')
  .option('--no-git', 'Skip git initialization')
  .action(async (projectName: string | undefined, options) => {
    console.log(
      chalk.bold.green('\n┌─────────────────────────────────┐')
    );
    console.log(
      chalk.bold.green('│  ') +
        chalk.white('FABRK CREATE') +
        chalk.bold.green('                │')
    );
    console.log(
      chalk.bold.green('└─────────────────────────────────┘\n')
    );

    const responses = await prompts(
      [
        {
          type: projectName ? null : 'text',
          name: 'projectName',
          message: 'Project name:',
          initial: 'my-fabrk-app',
          validate: (value: string) =>
            /^[a-z0-9-]+$/.test(value)
              ? true
              : 'Project name must be lowercase with hyphens only',
        },
        {
          type: options.template ? null : 'select',
          name: 'template',
          message: 'Select a template:',
          choices: TEMPLATES,
          initial: 0,
        },
      ],
      {
        onCancel: () => {
          console.log(chalk.red('\n✗ Cancelled'));
          process.exit(0);
        },
      }
    );

    projectName = projectName || responses.projectName;
    const template = options.template || responses.template;
    const targetDir = path.resolve(process.cwd(), projectName!);

    if (fs.existsSync(targetDir)) {
      console.log(chalk.red(`\n✗ Directory "${projectName}" already exists`));
      process.exit(1);
    }

    const templatesDir = path.resolve(__dirname, '../templates');
    const templateDir = path.join(templatesDir, template);

    if (!fs.existsSync(templateDir)) {
      console.log(chalk.red(`\n✗ Template "${template}" not found`));
      process.exit(1);
    }

    const spinner = ora('Creating project...').start();

    try {
      await fs.copy(templateDir, targetDir);
      spinner.succeed('Project created');

      const packageJsonPath = path.join(targetDir, 'package.json');
      if (fs.existsSync(packageJsonPath)) {
        const packageJson = await fs.readJson(packageJsonPath);
        packageJson.name = projectName;
        await fs.writeJson(packageJsonPath, packageJson, { spaces: 2 });
      }

      if (options.install !== false) {
        spinner.start('Installing dependencies...');
        execSync('pnpm install', { cwd: targetDir, stdio: 'ignore' });
        spinner.succeed('Dependencies installed');
      }

      if (options.git !== false) {
        spinner.start('Initializing git...');
        execSync('git init', { cwd: targetDir, stdio: 'ignore' });
        execSync('git add .', { cwd: targetDir, stdio: 'ignore' });
        execSync('git commit -m "Initial commit from fabrk create"', {
          cwd: targetDir,
          stdio: 'ignore',
        });
        spinner.succeed('Git initialized');
      }

      // Generate .fabrk/ directory
      generateFabrkDir({ root: targetDir, configPath: null });

      console.log(
        chalk.green.bold('\n✓ Success!') +
          chalk.dim(' Your FABRK app is ready.\n')
      );
      console.log(chalk.bold('Next steps:\n'));
      console.log(chalk.cyan(`  cd ${projectName}`));
      console.log(chalk.cyan('  fabrk dev'));
      console.log();
      console.log(chalk.dim('  Open http://localhost:3000 to view your app'));
      console.log(chalk.dim('  Edit fabrk.config.ts to configure your app\n'));
    } catch (error) {
      spinner.fail('Failed to create project');
      console.error(chalk.red('\nError:'), error instanceof Error ? error.message : error);
      process.exit(1);
    }
  });

// ============================================================================
// COMMAND: fabrk dev
// ============================================================================

program
  .command('dev')
  .description('Start development server with FABRK config validation')
  .option('-p, --port <port>', 'Port number', '3000')
  .action((options) => {
    const root = findProjectRoot();
    const configPath = hasFabrkConfig(root) ? 'fabrk.config.ts' : null;

    if (configPath) {
      console.log(chalk.green('[FABRK]') + chalk.dim(` Config detected: ${configPath}`));
    } else {
      console.log(chalk.yellow('[FABRK]') + chalk.dim(' No fabrk.config.ts found — using defaults'));
    }

    // Generate .fabrk/ directory
    generateFabrkDir({ root, configPath });

    console.log(chalk.green('[FABRK]') + chalk.dim(` Starting dev server on port ${options.port}...\n`));
    runCommand('npx', ['next', 'dev', '-p', options.port], root);
  });

// ============================================================================
// COMMAND: fabrk build
// ============================================================================

program
  .command('build')
  .description('Build the FABRK application with config validation')
  .action(() => {
    const root = findProjectRoot();
    const configPath = hasFabrkConfig(root) ? 'fabrk.config.ts' : null;

    if (configPath) {
      console.log(chalk.green('[FABRK]') + chalk.dim(` Config validated: ${configPath}`));
    } else {
      console.log(chalk.yellow('[FABRK]') + chalk.dim(' No fabrk.config.ts found — using defaults'));
    }

    // Generate .fabrk/ directory
    generateFabrkDir({ root, configPath });

    console.log(chalk.green('[FABRK]') + chalk.dim(' Building...\n'));
    runCommand('npx', ['next', 'build'], root);
  });

// ============================================================================
// COMMAND: fabrk start
// ============================================================================

program
  .command('start')
  .description('Start production server')
  .option('-p, --port <port>', 'Port number', '3000')
  .action((options) => {
    const root = findProjectRoot();
    console.log(chalk.green('[FABRK]') + chalk.dim(` Starting production server on port ${options.port}...\n`));
    runCommand('npx', ['next', 'start', '-p', options.port], root);
  });

// ============================================================================
// COMMAND: fabrk add <components...>
// ============================================================================

program
  .command('add [components...]')
  .description('Add UI components to your project (shadcn-style copy)')
  .option('--dir <dir>', 'Target directory', 'src/components/ui')
  .action((components: string[], options) => {
    const root = findProjectRoot();
    const targetDir = path.resolve(root, options.dir);

    if (!components || components.length === 0) {
      console.log(chalk.yellow('[FABRK]') + chalk.dim(' Usage: fabrk add button card dialog'));
      console.log(chalk.dim('\nAvailable components can be browsed at the component registry.'));
      return;
    }

    // Check for feature module adds (auth, payments, etc.)
    const featureModules = components.filter(c => (FEATURE_MODULES as readonly string[]).includes(c));
    const uiComponents = components.filter(c => !(FEATURE_MODULES as readonly string[]).includes(c));

    // Handle feature module additions
    for (const mod of featureModules) {
      addFeatureModule(root, mod);
    }

    // Handle UI component additions
    if (uiComponents.length > 0) {
      addUIComponents(root, uiComponents, targetDir);
    }
  });

function addFeatureModule(root: string, moduleName: string): void {
  const pkgName = `@fabrk/${moduleName}`;
  const spinner = ora(`Adding ${pkgName}...`).start();

  try {
    execSync(`pnpm add ${pkgName}`, { cwd: root, stdio: 'ignore' });
    spinner.succeed(`Added ${pkgName}`);

    // Update fabrk.config.ts hint
    console.log(chalk.dim(`  Update fabrk.config.ts to configure ${moduleName}`));
  } catch {
    spinner.fail(`Failed to add ${pkgName}`);
    console.log(chalk.dim(`  You may need to install it manually: pnpm add ${pkgName}`));
  }
}

function addUIComponents(root: string, components: string[], targetDir: string): void {
  // Look for component files in the registry
  const registryPaths = [
    path.resolve(__dirname, '../registry'),
    path.resolve(__dirname, '../../registry'),
  ];

  let registryDir: string | null = null;
  for (const p of registryPaths) {
    if (fs.existsSync(p)) {
      registryDir = p;
      break;
    }
  }

  if (!registryDir) {
    // Fallback: generate basic component scaffolds
    console.log(chalk.yellow('[FABRK]') + chalk.dim(' Component registry not found — generating scaffolds'));
    fs.ensureDirSync(targetDir);

    for (const component of components) {
      const fileName = toKebabCase(component);
      const componentName = toPascalCase(component);
      const filePath = path.join(targetDir, `${fileName}.tsx`);

      if (fs.existsSync(filePath)) {
        console.log(chalk.yellow('  ⚠') + chalk.dim(` ${fileName}.tsx already exists — skipping`));
        continue;
      }

      fs.writeFileSync(filePath, generateComponentTemplate(componentName));
      console.log(chalk.green('  ✓') + chalk.dim(` Created ${path.relative(root, filePath)}`));
    }
    return;
  }

  // Copy from registry
  fs.ensureDirSync(targetDir);

  for (const component of components) {
    const fileName = toKebabCase(component);
    const sourcePaths = [
      path.join(registryDir, 'ui', `${fileName}.tsx`),
      path.join(registryDir, 'charts', `${fileName}.tsx`),
      path.join(registryDir, 'ai', `${fileName}.tsx`),
      path.join(registryDir, 'admin', `${fileName}.tsx`),
      path.join(registryDir, 'security', `${fileName}.tsx`),
      path.join(registryDir, 'organization', `${fileName}.tsx`),
      path.join(registryDir, 'seo', `${fileName}.tsx`),
    ];

    let copied = false;
    for (const src of sourcePaths) {
      if (fs.existsSync(src)) {
        const dest = path.join(targetDir, `${fileName}.tsx`);
        if (fs.existsSync(dest)) {
          console.log(chalk.yellow('  ⚠') + chalk.dim(` ${fileName}.tsx already exists — skipping`));
          copied = true;
          break;
        }
        fs.copyFileSync(src, dest);
        console.log(chalk.green('  ✓') + chalk.dim(` Copied ${fileName}.tsx`));
        copied = true;
        break;
      }
    }

    if (!copied) {
      // Generate scaffold if not in registry
      const componentName = toPascalCase(component);
      const dest = path.join(targetDir, `${fileName}.tsx`);
      fs.writeFileSync(dest, generateComponentTemplate(componentName));
      console.log(chalk.green('  ✓') + chalk.dim(` Generated ${fileName}.tsx (scaffold)`));
    }
  }
}

// ============================================================================
// COMMAND: fabrk add-theme
// ============================================================================

program
  .command('add-theme [theme]')
  .description('Install or switch design system theme')
  .action(async (theme: string | undefined) => {
    const root = findProjectRoot();

    if (!theme) {
      const response = await prompts({
        type: 'select',
        name: 'theme',
        message: 'Select a theme:',
        choices: [
          { title: 'Terminal', value: 'terminal', description: 'Monospace, sharp corners, green-on-black' },
          { title: 'Swiss', value: 'swiss', description: 'Clean, grid-based, industrial design' },
        ],
      });
      theme = response.theme;
    }

    if (!theme || !(AVAILABLE_THEMES as readonly string[]).includes(theme)) {
      console.log(chalk.red(`✗ Unknown theme: ${theme}`));
      console.log(chalk.dim(`Available: ${AVAILABLE_THEMES.join(', ')}`));
      return;
    }

    const spinner = ora(`Setting up ${theme} theme...`).start();

    try {
      // Ensure @fabrk/themes is installed
      const pkgPath = path.join(root, 'package.json');
      if (fs.existsSync(pkgPath)) {
        const pkg = fs.readJsonSync(pkgPath);
        const allDeps = { ...pkg.dependencies, ...pkg.devDependencies };
        if (!allDeps['@fabrk/themes'] && !allDeps['@fabrk/design-system']) {
          execSync('pnpm add @fabrk/themes', { cwd: root, stdio: 'ignore' });
        }
      }

      // Generate CSS variables file
      const cssDir = path.join(root, 'src', 'styles');
      fs.ensureDirSync(cssDir);

      const cssPath = path.join(cssDir, 'theme.css');
      if (!fs.existsSync(cssPath)) {
        fs.writeFileSync(cssPath, generateThemeCSS(theme));
        spinner.succeed(`Theme "${theme}" installed`);
        console.log(chalk.dim(`  Created ${path.relative(root, cssPath)}`));
        console.log(chalk.dim(`  Import it in your layout: import '@/styles/theme.css'`));
      } else {
        spinner.succeed(`Theme "${theme}" configured`);
        console.log(chalk.dim(`  ${path.relative(root, cssPath)} already exists — update manually if needed`));
      }
    } catch (error) {
      spinner.fail('Failed to set up theme');
      console.error(chalk.red(error instanceof Error ? error.message : String(error)));
    }
  });

function generateThemeCSS(theme: string): string {
  if (theme === 'terminal') {
    return `/* FABRK Terminal Theme */
@import "tailwindcss";

:root {
  --background: 0 0% 3%;
  --foreground: 120 100% 80%;
  --card: 0 0% 6%;
  --card-foreground: 120 60% 70%;
  --popover: 0 0% 8%;
  --popover-foreground: 120 100% 80%;
  --primary: 120 100% 50%;
  --primary-foreground: 0 0% 0%;
  --secondary: 0 0% 12%;
  --secondary-foreground: 120 60% 70%;
  --muted: 0 0% 12%;
  --muted-foreground: 120 20% 50%;
  --accent: 270 60% 60%;
  --accent-foreground: 0 0% 100%;
  --destructive: 0 84% 60%;
  --destructive-foreground: 0 0% 100%;
  --success: 120 100% 40%;
  --success-foreground: 0 0% 0%;
  --warning: 45 100% 50%;
  --warning-foreground: 0 0% 0%;
  --info: 200 100% 50%;
  --info-foreground: 0 0% 0%;
  --border: 120 20% 20%;
  --input: 0 0% 12%;
  --ring: 120 100% 50%;
  --radius: 0px;
  font-family: 'JetBrains Mono', 'Fira Code', 'Consolas', monospace;
}
`;
  }

  // Swiss theme
  return `/* FABRK Swiss Theme */
@import "tailwindcss";

:root {
  --background: 0 0% 98%;
  --foreground: 0 0% 12%;
  --card: 0 0% 100%;
  --card-foreground: 0 0% 12%;
  --popover: 0 0% 100%;
  --popover-foreground: 0 0% 12%;
  --primary: 0 0% 12%;
  --primary-foreground: 0 0% 98%;
  --secondary: 0 0% 94%;
  --secondary-foreground: 0 0% 12%;
  --muted: 0 0% 94%;
  --muted-foreground: 0 0% 50%;
  --accent: 0 84% 60%;
  --accent-foreground: 0 0% 100%;
  --destructive: 0 84% 60%;
  --destructive-foreground: 0 0% 100%;
  --success: 142 72% 40%;
  --success-foreground: 0 0% 100%;
  --warning: 38 92% 50%;
  --warning-foreground: 0 0% 0%;
  --info: 217 91% 60%;
  --info-foreground: 0 0% 100%;
  --border: 0 0% 88%;
  --input: 0 0% 94%;
  --ring: 0 0% 12%;
  --radius: 4px;
  font-family: 'Helvetica Neue', 'Arial', sans-serif;
}
`;
}

// ============================================================================
// COMMAND: fabrk lint
// ============================================================================

program
  .command('lint')
  .description('Lint for FABRK design system compliance')
  .option('--fix', 'Attempt to fix issues automatically')
  .option('--dir <dir>', 'Directory to lint', 'src')
  .action(async (options) => {
    const root = findProjectRoot();
    const targetDir = path.resolve(root, options.dir);
    const spinner = ora('Scanning for design system violations...').start();

    if (!fs.existsSync(targetDir)) {
      const appDir = path.resolve(root, 'app');
      if (!fs.existsSync(appDir)) {
        spinner.fail(`Directory not found: ${options.dir}`);
        process.exit(1);
      }
    }

    const files = findFiles(targetDir, ['.tsx', '.jsx']);

    if (files.length === 0) {
      spinner.info('No TSX/JSX files found');
      return;
    }

    spinner.text = `Linting ${files.length} files...`;

    let totalIssues = 0;
    const results: Array<{ file: string; issues: string[] }> = [];

    for (const file of files) {
      const content = fs.readFileSync(file, 'utf-8');
      const issues: string[] = [];

      const colorRegex = /(?:bg|text|border)-(?:red|blue|green|yellow|purple|pink|orange|indigo|gray|slate|zinc|neutral|stone|amber|lime|emerald|teal|cyan|sky|violet|fuchsia|rose)-\d{2,3}/g;
      const colorMatches = content.match(colorRegex);
      if (colorMatches) {
        const unique = [...new Set(colorMatches)];
        issues.push(`Hardcoded colors: ${unique.slice(0, 3).join(', ')}${unique.length > 3 ? ` (+${unique.length - 3} more)` : ''}`);
      }

      const radiusRegex = /\brounded-(?:sm|md|lg|xl|2xl|3xl|full)\b/g;
      const radiusMatches = content.match(radiusRegex);
      if (radiusMatches) {
        const nonSwitchRadius = radiusMatches.filter(r => r !== 'rounded-full');
        if (nonSwitchRadius.length > 0) {
          issues.push(`Hardcoded radius (use mode.radius): ${[...new Set(nonSwitchRadius)].join(', ')}`);
        }
      }

      const inlineStyleRegex = /style\s*=\s*\{\{/g;
      const inlineMatches = content.match(inlineStyleRegex);
      if (inlineMatches) {
        issues.push(`Inline styles found (${inlineMatches.length} occurrences)`);
      }

      if (content.includes('dangerouslySetInnerHTML')) {
        issues.push('dangerouslySetInnerHTML usage detected');
      }

      if (issues.length > 0) {
        totalIssues += issues.length;
        results.push({ file: path.relative(root, file), issues });
      }
    }

    if (totalIssues === 0) {
      spinner.succeed(chalk.green(`All ${files.length} files pass FABRK lint`));
    } else {
      spinner.warn(chalk.yellow(`Found ${totalIssues} issues in ${results.length} files`));
      console.log();
      for (const result of results) {
        console.log(chalk.bold(result.file));
        for (const issue of result.issues) {
          console.log(chalk.dim('  ') + chalk.yellow('⚠') + chalk.dim(` ${issue}`));
        }
        console.log();
      }
    }
  });

// ============================================================================
// COMMAND: fabrk generate
// ============================================================================

const generate = program
  .command('generate')
  .alias('g')
  .description('Generate FABRK files from templates');

generate
  .command('component <name>')
  .description('Generate a new UI component')
  .option('--dir <dir>', 'Target directory', 'src/components')
  .action((name: string, options) => {
    const root = findProjectRoot();
    const componentDir = path.resolve(root, options.dir);
    const fileName = toKebabCase(name);
    const componentName = toPascalCase(name);
    const filePath = path.join(componentDir, `${fileName}.tsx`);

    if (fs.existsSync(filePath)) {
      console.log(chalk.red(`✗ Component already exists: ${filePath}`));
      process.exit(1);
    }

    fs.ensureDirSync(componentDir);
    fs.writeFileSync(filePath, generateComponentTemplate(componentName));
    console.log(chalk.green('✓') + chalk.dim(` Created ${path.relative(root, filePath)}`));
  });

generate
  .command('page <name>')
  .description('Generate a new page')
  .option('--dir <dir>', 'Target directory', 'app')
  .action((name: string, options) => {
    const root = findProjectRoot();
    const pageName = toKebabCase(name);
    const pageDir = path.resolve(root, options.dir, pageName);
    const filePath = path.join(pageDir, 'page.tsx');

    if (fs.existsSync(filePath)) {
      console.log(chalk.red(`✗ Page already exists: ${filePath}`));
      process.exit(1);
    }

    fs.ensureDirSync(pageDir);
    fs.writeFileSync(filePath, generatePageTemplate(toPascalCase(name)));
    console.log(chalk.green('✓') + chalk.dim(` Created ${path.relative(root, filePath)}`));
  });

generate
  .command('api <name>')
  .description('Generate a new API route')
  .option('--dir <dir>', 'Target directory', 'app/api')
  .action((name: string, options) => {
    const root = findProjectRoot();
    const routeName = toKebabCase(name);
    const routeDir = path.resolve(root, options.dir, routeName);
    const filePath = path.join(routeDir, 'route.ts');

    if (fs.existsSync(filePath)) {
      console.log(chalk.red(`✗ API route already exists: ${filePath}`));
      process.exit(1);
    }

    fs.ensureDirSync(routeDir);
    fs.writeFileSync(filePath, generateApiTemplate(name));
    console.log(chalk.green('✓') + chalk.dim(` Created ${path.relative(root, filePath)}`));
  });

generate
  .command('ai-rules')
  .description('Generate CLAUDE.md / cursor rules from project config')
  .action(() => {
    const root = findProjectRoot();
    const filePath = path.join(root, 'CLAUDE.md');

    const manifest = generateManifest(root);
    const rules = generateAIRules(root, manifest);

    fs.writeFileSync(filePath, rules);
    console.log(chalk.green('✓') + chalk.dim(` Generated ${path.relative(root, filePath)}`));
    console.log(chalk.dim('  AI agents will use this file to understand your project'));
  });

function generateAIRules(root: string, manifest: object): string {
  const m = manifest as { name: string; packages: string[]; features: Record<string, boolean>; components: string[]; pages: string[] };
  const enabledFeatures = Object.entries(m.features)
    .filter(([_, v]) => v)
    .map(([k]) => k);

  return `# CLAUDE.md — ${m.name}

## Project Overview
This is a FABRK application built with the AI-first React meta-framework.

## Stack
- **Framework:** FABRK (wraps Next.js)
- **Language:** TypeScript (strict)
- **Styling:** Tailwind CSS + Design Tokens
- **FABRK Packages:** ${m.packages.join(', ') || 'none'}
- **Features:** ${enabledFeatures.join(', ') || 'none'}

## Commands
\`\`\`bash
fabrk dev          # Start dev server
fabrk build        # Production build
fabrk add <comp>   # Add UI components
fabrk lint         # Check design compliance
\`\`\`

## Design Rules
- Use design tokens only (bg-primary, text-foreground, border-border)
- No hardcoded colors (bg-blue-500, text-gray-100)
- Full borders get mode.radius, partial borders never get radius
- Labels: UPPERCASE in brackets [SECTION]
- Buttons: UPPERCASE with > prefix
- Headlines: UPPERCASE

## Key Files
- \`fabrk.config.ts\` — Framework configuration (single source of truth)
- \`src/components/ui/\` — UI components
- \`src/app/\` — Pages and API routes

## Components (${m.components.length})
${m.components.slice(0, 20).map(c => `- ${c}`).join('\n')}
${m.components.length > 20 ? `\n... and ${m.components.length - 20} more` : ''}

## Pages (${m.pages.length})
${m.pages.map(p => `- ${p}`).join('\n')}
`;
}

// ============================================================================
// COMMAND: fabrk doctor
// ============================================================================

program
  .command('doctor')
  .description('Diagnose FABRK project issues')
  .action(() => {
    const root = findProjectRoot();
    console.log(chalk.bold.green('\n[FABRK DOCTOR]\n'));

    let issues = 0;

    // Check package.json exists
    const pkgPath = path.join(root, 'package.json');
    if (fs.existsSync(pkgPath)) {
      console.log(chalk.green('  ✓') + chalk.dim(' package.json found'));
    } else {
      console.log(chalk.red('  ✗') + chalk.dim(' package.json not found'));
      issues++;
    }

    // Check fabrk.config.ts
    if (hasFabrkConfig(root)) {
      console.log(chalk.green('  ✓') + chalk.dim(' fabrk.config.ts found'));
    } else {
      console.log(chalk.yellow('  ⚠') + chalk.dim(' fabrk.config.ts not found (optional but recommended)'));
    }

    // Check @fabrk/core is installed
    if (fs.existsSync(pkgPath)) {
      const pkg = fs.readJsonSync(pkgPath);
      const allDeps = { ...pkg.dependencies, ...pkg.devDependencies };

      if (allDeps['@fabrk/core']) {
        console.log(chalk.green('  ✓') + chalk.dim(` @fabrk/core installed (${allDeps['@fabrk/core']})`));
      } else {
        console.log(chalk.red('  ✗') + chalk.dim(' @fabrk/core not installed'));
        issues++;
      }

      // Check for Next.js
      if (allDeps['next']) {
        console.log(chalk.green('  ✓') + chalk.dim(` next installed (${allDeps['next']})`));
      } else {
        console.log(chalk.red('  ✗') + chalk.dim(' next not installed (required runtime)'));
        issues++;
      }

      // Check for React 19
      if (allDeps['react']) {
        const reactVer = allDeps['react'];
        if (reactVer.includes('19') || reactVer.includes('^19')) {
          console.log(chalk.green('  ✓') + chalk.dim(` react ${reactVer}`));
        } else {
          console.log(chalk.yellow('  ⚠') + chalk.dim(` react ${reactVer} — FABRK recommends React 19`));
        }
      }

      // Check for Tailwind CSS
      if (allDeps['tailwindcss'] || allDeps['@tailwindcss/postcss']) {
        console.log(chalk.green('  ✓') + chalk.dim(' Tailwind CSS installed'));
      } else {
        console.log(chalk.yellow('  ⚠') + chalk.dim(' Tailwind CSS not found'));
      }

      // Check for TypeScript
      if (allDeps['typescript']) {
        console.log(chalk.green('  ✓') + chalk.dim(` typescript installed (${allDeps['typescript']})`));
      } else {
        console.log(chalk.yellow('  ⚠') + chalk.dim(' typescript not found'));
      }
    }

    // Check node_modules exists
    if (fs.existsSync(path.join(root, 'node_modules'))) {
      console.log(chalk.green('  ✓') + chalk.dim(' node_modules exists'));
    } else {
      console.log(chalk.red('  ✗') + chalk.dim(' node_modules not found — run pnpm install'));
      issues++;
    }

    // Check .fabrk/ directory
    if (fs.existsSync(path.join(root, '.fabrk'))) {
      console.log(chalk.green('  ✓') + chalk.dim(' .fabrk/ directory exists'));
    } else {
      console.log(chalk.dim('  ○') + chalk.dim(' .fabrk/ not generated yet (run fabrk dev)'));
    }

    console.log();
    if (issues === 0) {
      console.log(chalk.green.bold('  All checks passed!'));
    } else {
      console.log(chalk.yellow(`  ${issues} issue(s) found`));
    }
    console.log();
  });

// ============================================================================
// COMMAND: fabrk upgrade
// ============================================================================

program
  .command('upgrade')
  .description('Upgrade FABRK packages to latest versions')
  .action(() => {
    const root = findProjectRoot();
    const pkgPath = path.join(root, 'package.json');

    if (!fs.existsSync(pkgPath)) {
      console.log(chalk.red('✗ No package.json found'));
      process.exit(1);
    }

    const pkg = fs.readJsonSync(pkgPath);
    const allDeps = { ...pkg.dependencies, ...pkg.devDependencies };
    const fabrkDeps = Object.keys(allDeps).filter(d => d.startsWith('@fabrk/'));

    if (fabrkDeps.length === 0) {
      console.log(chalk.yellow('No @fabrk/ packages found'));
      return;
    }

    const spinner = ora(`Upgrading ${fabrkDeps.length} FABRK packages...`).start();

    try {
      execSync(`pnpm update ${fabrkDeps.join(' ')}`, { cwd: root, stdio: 'ignore' });
      spinner.succeed(`Upgraded ${fabrkDeps.length} packages: ${fabrkDeps.join(', ')}`);
    } catch {
      spinner.fail('Failed to upgrade packages');
    }
  });

// ============================================================================
// COMMAND: fabrk info
// ============================================================================

program
  .command('info')
  .description('Show FABRK project information')
  .action(() => {
    const root = findProjectRoot();
    const hasConfig = hasFabrkConfig(root);
    const pkgPath = path.join(root, 'package.json');

    console.log(chalk.bold.green('\n[FABRK PROJECT INFO]\n'));

    if (fs.existsSync(pkgPath)) {
      const pkg = fs.readJsonSync(pkgPath);
      console.log(chalk.dim('  Name:    ') + pkg.name);
      console.log(chalk.dim('  Version: ') + (pkg.version || 'N/A'));

      const allDeps = { ...pkg.dependencies, ...pkg.devDependencies };
      const fabrkDeps = Object.keys(allDeps).filter(d => d.startsWith('@fabrk/'));
      if (fabrkDeps.length > 0) {
        console.log(chalk.dim('  Packages:'));
        for (const dep of fabrkDeps) {
          console.log(chalk.dim('    ') + chalk.cyan(dep) + chalk.dim(` ${allDeps[dep]}`));
        }
      }
    }

    console.log(chalk.dim('  Config:  ') + (hasConfig ? chalk.green('fabrk.config.ts') : chalk.yellow('none')));
    console.log(chalk.dim('  Root:    ') + root);
    console.log();
  });

program.parse();

// ============================================================================
// CODE TEMPLATES
// ============================================================================

function generateComponentTemplate(name: string): string {
  return `'use client'

import { cn } from '@fabrk/core'

export interface ${name}Props {
  className?: string
  children?: React.ReactNode
}

export function ${name}({ className, children }: ${name}Props) {
  return (
    <div
      className={cn(
        'border border-border bg-card p-4',
        className
      )}
    >
      {children}
    </div>
  )
}
`;
}

function generatePageTemplate(name: string): string {
  return `export default function ${name}Page() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-center p-8">
      <h1 className="text-2xl font-bold tracking-tight">
        ${name.replace(/([A-Z])/g, ' $1').trim().toUpperCase()}
      </h1>
    </main>
  )
}
`;
}

function generateApiTemplate(name: string): string {
  return `import { NextResponse } from 'next/server'

export async function GET() {
  return NextResponse.json({
    message: '${name} endpoint',
  })
}

export async function POST(request: Request) {
  const body = await request.json()

  return NextResponse.json({
    message: '${name} created',
    data: body,
  })
}
`;
}
